// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityLibraryMVC.Models;

#nullable disable

namespace UniversityLibraryMVC.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260114160703_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityLibraryMVC.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("int");

                    b.Property<int>("UniversityID")
                        .HasColumnType("int");

                    b.HasKey("BookID");

                    b.HasIndex("UniversityID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "John Smith",
                            AvailableCopies = 5,
                            Category = "Computer Science",
                            ISBN = "978-3-16-148410-0",
                            PublicationYear = 2022,
                            Publisher = "Tech Press",
                            Title = "Introduction to Computer Science",
                            TotalCopies = 5,
                            UniversityID = 1
                        },
                        new
                        {
                            BookID = 2,
                            Author = "Jane Doe",
                            AvailableCopies = 3,
                            Category = "Databases",
                            ISBN = "978-1-56-619909-4",
                            PublicationYear = 2023,
                            Publisher = "Data Books",
                            Title = "Database Systems",
                            TotalCopies = 3,
                            UniversityID = 1
                        },
                        new
                        {
                            BookID = 3,
                            Author = "Robert Brown",
                            AvailableCopies = 4,
                            Category = "Web Development",
                            ISBN = "978-0-26-203384-8",
                            PublicationYear = 2021,
                            Publisher = "Web Publishing",
                            Title = "Web Development Fundamentals",
                            TotalCopies = 4,
                            UniversityID = 1
                        });
                });

            modelBuilder.Entity("UniversityLibraryMVC.Models.Loan", b =>
                {
                    b.Property<int>("LoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LoanID");

                    b.HasIndex("BookID");

                    b.HasIndex("MemberID");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("UniversityLibraryMVC.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MembershipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UniversityID")
                        .HasColumnType("int");

                    b.HasKey("MemberID");

                    b.HasIndex("UniversityID");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            Email = "ahmed.hassan@meu.edu",
                            IsActive = true,
                            MembershipDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ahmed Hassan",
                            Phone = "555-1234",
                            StudentID = "MU2024001",
                            UniversityID = 1
                        },
                        new
                        {
                            MemberID = 2,
                            Email = "sara.mahmoud@meu.edu",
                            IsActive = true,
                            MembershipDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sara Mahmoud",
                            Phone = "555-5678",
                            StudentID = "MU2024002",
                            UniversityID = 1
                        },
                        new
                        {
                            MemberID = 3,
                            Email = "mohammed.ali@meu.edu",
                            IsActive = true,
                            MembershipDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mohammed Ali",
                            Phone = "555-9012",
                            StudentID = "MU2024003",
                            UniversityID = 1
                        });
                });

            modelBuilder.Entity("UniversityLibraryMVC.Models.University", b =>
                {
                    b.Property<int>("UniversityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UniversityID"));

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuPosition")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniversityID");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            UniversityID = 1,
                            LogoPath = "/images/meu-university-logo.png",
                            MenuPosition = 1,
                            Name = "Meu University",
                            PrimaryColor = "#003366",
                            SecondaryColor = "#FFD700"
                        });
                });

            modelBuilder.Entity("UniversityLibraryMVC.Models.Book", b =>
                {
                    b.HasOne("UniversityLibraryMVC.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniversityLibraryMVC.Models.Loan", b =>
                {
                    b.HasOne("UniversityLibraryMVC.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityLibraryMVC.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("UniversityLibraryMVC.Models.Member", b =>
                {
                    b.HasOne("UniversityLibraryMVC.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });
#pragma warning restore 612, 618
        }
    }
}
